// <auto-generated />
using System;
using FileSort.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileSort.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250323232807_InstanceIndex")]
    partial class InstanceIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileSort.DataModels.ApplicationInstance", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosingTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InitiationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ApplicationId");

                    b.HasIndex("InitiationTime")
                        .IsUnique();

                    b.ToTable("ApplicationInstances");
                });

            modelBuilder.Entity("FileSort.DataModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FileSort.DataModels.Extension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ExtensionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExtensionName")
                        .IsUnique();

                    b.ToTable("Extensions");
                });

            modelBuilder.Entity("FileSort.DataModels.FileDataModel", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ExtensionId")
                        .HasColumnType("int");

                    b.Property<string>("SourceFolderPath")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ApplicationInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DestinationFolderPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSorted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("SortDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("FileName", "ExtensionId", "SourceFolderPath");

                    b.HasIndex("ApplicationInstanceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExtensionId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("FileSort.DataModels.Extension", b =>
                {
                    b.HasOne("FileSort.DataModels.Category", "Category")
                        .WithMany("Extensions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FileSort.DataModels.FileDataModel", b =>
                {
                    b.HasOne("FileSort.DataModels.ApplicationInstance", "ApplicationInstance")
                        .WithMany("Files")
                        .HasForeignKey("ApplicationInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileSort.DataModels.Category", "Category")
                        .WithMany("Files")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FileSort.DataModels.Extension", "FileExtension")
                        .WithMany("Files")
                        .HasForeignKey("ExtensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationInstance");

                    b.Navigation("Category");

                    b.Navigation("FileExtension");
                });

            modelBuilder.Entity("FileSort.DataModels.ApplicationInstance", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("FileSort.DataModels.Category", b =>
                {
                    b.Navigation("Extensions");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("FileSort.DataModels.Extension", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
